# Topics 
#### List Operations  (Done)
#### Numpy Operations (Done)
#### pandas Operations (Done)
#### Lambda, Map, Reduce, Filter, List Comprehension, applymap Operations (Done)
#### Loops and conditionals (Done)
#### Regular Expression (in progress)
#### Classes Object and Self (Done)
#### Inheritance (Done)
#### Module creation, module binding__init__.py file, module loading
#### Python Coding Practise (in progress)
#### Model Deployment - Flask & Django
#### Custom Loss Function in Light GBM (Done) & Keras
#### Hyperopt Parameter Tuning:  (Done)
    ##### 1. Using Hyperopt (Done)
    ##### 2. Stacking Ensemble (Done)
    ##### 3. NN Ensemble(Done)
#### ML Pipeline (Done)
#### End-to-End Python Package Building (customdnn):
    #### link : https://github.com/singhmnprt01/Custom-Deep-Neural-Network-Package
#### Tensorflow 2.0
#### Pyspark
#### Transfer Learning

In [1]:
import pandas as pd
import numpy as np
import functools

# List operations

In [562]:
my_list = [1,2,3,4,5,6,7,8,9]

In [566]:
print(f"{my_list[0]} {my_list[-1]} {my_list[2:4]}")

1 9 [3, 4]


In [62]:
xyz = ('a','b','c')

In [63]:
type(xyz)

tuple

#### List vs Tuple 

#### Replace an item

In [97]:
my_list[0]=10
my_list

[10, 2, 3, 4, 5, 6, 7, 8, 9]

#### Add an item

In [98]:
my_list.append(1)
my_list

[10, 2, 3, 4, 5, 6, 7, 8, 9, 1]

#### Append two lists

In [99]:
my_list[0:4] + my_list[5:9]

[10, 2, 3, 4, 6, 7, 8, 9]

#### Insert in between without replacement

In [100]:
my_list.insert(5,100)

In [101]:
my_list

[10, 2, 3, 4, 5, 100, 6, 7, 8, 9, 1]

#### Delete an item or an item at a particular index

In [102]:
del my_list[5]
my_list

[10, 2, 3, 4, 5, 6, 7, 8, 9, 1]

In [103]:
my_list.remove(int(5))

In [104]:
my_list

[10, 2, 3, 4, 6, 7, 8, 9, 1]

In [105]:
my_list.pop(0)

10

In [106]:
my_list

[2, 3, 4, 6, 7, 8, 9, 1]

#### Sort

In [511]:
my_list.sort()
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
my_list.sort(reverse=True)
my_list

[9, 8, 7, 6, 4, 3, 2, 1]

In [109]:
my_list

[9, 8, 7, 6, 4, 3, 2, 1]

In [513]:
mylist_2 = my_list.copy()

In [516]:
mylist_2.sort(reverse=True)
mylist_2

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [518]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [517]:
mylist_2 == my_list

False

In [519]:
x = ['c','b']
y = ['b','c']
x==y

False

#### Get index of matched element

In [110]:
my_index = my_list.index(2)
my_index

6

In [111]:
my_index_beg = my_list.index(8,1,5) ## Search for 8 between 1st and 5th index
my_index_beg

1

#### Search an item in the list and replace it 

In [112]:
i=6
if i in my_list:
    print(f"{i} is present in the list at {my_list.index(i)} location\n")
    k = my_list.index(i)
    my_list[k]= k
    print(f"{i} as been replaced with {k} at {k}")

6 is present in the list at 3 location

6 as been replaced with 3 at 3


##### List to DataFrame

In [113]:
df = pd.DataFrame(my_list,columns=["Customer Ranking"])
df.head()

Customer Ranking
0                 9
1                 8
2                 7
3                 3
4                 4

#### Delete all elements or clear a list 

In [114]:
my_list.clear()
my_list

[]

# Numpy Operations

In [507]:
import numpy as np

In [116]:
np.__version__

'1.19.1'

#### Ways to create an array

In [118]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [119]:
z[1]=2
z

array([0., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
z[::-1] ## Reverse an Array !

array([0., 0., 0., 0., 0., 0., 0., 0., 2., 0.])

In [125]:
print(np.nonzero(z))

(array([1]),)


In [178]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
np.random.random(9).reshape(3,3)

array([[0.35745207, 0.25270313, 0.11235058],
       [0.2391219 , 0.9767954 , 0.532344  ],
       [0.93861748, 0.76574057, 0.03736928]])

In [180]:
np.random.random((3,3))

array([[0.96843703, 0.59701106, 0.04863256],
       [0.28808623, 0.11019234, 0.03357907],
       [0.91061037, 0.28723523, 0.30295854]])

In [182]:
np.random.rand(9).reshape(3,3)

array([[0.61711766, 0.88426366, 0.48621273],
       [0.35874715, 0.2345637 , 0.01154014],
       [0.77618546, 0.93095271, 0.6641293 ]])

In [214]:
np.random.uniform(1,100,9).reshape(3,3)

array([[55.82063041, 28.60233942, 20.94007609],
       [ 6.68031718, 99.67419693, 15.07821482],
       [61.2805433 , 32.00139865, 24.12364458]])

In [310]:
np.random.uniform(1,100,(3,3))

array([[54.27246699, 29.53449056, 42.87386175],
       [18.38652284,  7.76944544, 18.1874872 ],
       [41.08779269, 57.74377288, 37.8037022 ]])

In [216]:
np.random.randint(1,100,(3,3))

array([[94, 71,  2],
       [45, 95, 80],
       [ 9, 56,  3]])

In [126]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Tricky questions and fun facts

In [217]:
0*np.nan

nan

In [218]:
np.nan==np.nan

False

In [222]:
np.inf < np.nan, np.inf > np.nan , np.inf == np.nan

(False, False, False)

In [223]:
np.nan - np.nan

nan

In [224]:
np.nan +  np.nan

nan

In [228]:
.3 == 3*.1

False

In [230]:
3*.1

0.30000000000000004

In [229]:
.3 == round(3*.1,1)

True

In [232]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [237]:
np.diag(1+np.arange(4),k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [234]:
np.diag(1+np.arange(4),k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

#### Get index value of 100th element in a x.y.z shape array

In [504]:
np.unravel_index(100,(2,7,8))

(1, 5, 4)

In [252]:
z = np.random.random((5,5))
print(z)

[[0.06675363 0.02224997 0.01023974 0.63496286 0.48011928]
 [0.7965146  0.33422336 0.78905098 0.25619279 0.51858275]
 [0.10968468 0.38954964 0.67143225 0.26520413 0.32352056]
 [0.86242624 0.87865676 0.31745363 0.34651976 0.66393973]
 [0.86882568 0.07066111 0.80285235 0.57713405 0.64642782]]


In [253]:
z_min,z_max =z.min(),z.max() 

In [254]:
z = (z-z_min)/(z_max-z_min)
print(z)

[[0.06507691 0.01383003 0.         0.71938148 0.54107592]
 [0.90541162 0.37307378 0.89681711 0.28321998 0.5853674 ]
 [0.11451288 0.43678313 0.76137674 0.29359672 0.36074929]
 [0.98131022 1.         0.35376309 0.38723334 0.75274894]
 [0.98867932 0.06957645 0.91270967 0.65279042 0.73258362]]


#### 2 ways to to dot product of arrays

In [249]:
## 1
np.dot(np.random.randint(1,10,(5,2)),np.random.randint(11,20,(2,3))) ## Dot Product wau 1

array([[ 80,  84,  89],
       [ 52,  48,  51],
       [ 52,  48,  51],
       [164, 192, 203],
       [117, 141, 149]])

In [318]:
## 2
np.random.randint(1,10,(5,2))@np.random.randint(11,20,(2,3)) ## Dot Prodict way 2

array([[262, 263, 211],
       [107, 108,  86],
       [200, 201, 161],
       [251, 249, 203],
       [206, 203, 167]])

#### conditonal array printng

In [255]:
z[z>.5]

array([0.71938148, 0.54107592, 0.90541162, 0.89681711, 0.5853674 ,
       0.76137674, 0.98131022, 1.        , 0.75274894, 0.98867932,
       0.91270967, 0.65279042, 0.73258362])

In [256]:
z[(z>.2)&(z>.8)] *= -1
z

array([[ 0.06507691,  0.01383003,  0.        ,  0.71938148,  0.54107592],
       [-0.90541162,  0.37307378, -0.89681711,  0.28321998,  0.5853674 ],
       [ 0.11451288,  0.43678313,  0.76137674,  0.29359672,  0.36074929],
       [-0.98131022, -1.        ,  0.35376309,  0.38723334,  0.75274894],
       [-0.98867932,  0.06957645, -0.91270967,  0.65279042,  0.73258362]])

In [262]:
sum(range(0,5)) ## 0 + 1 + 2 + 3 + 4 

10

In [264]:
sum(range(2,5)) ## 2 + 3 + 4 = 9

9

In [268]:
z**z

/Users/manpreetsi/opt/anaconda3/envs/deeplearning_practise/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


array([[ 0.837108  ,  0.94251338,  1.        ,  0.78904021,  0.71725311],
       [        nan,  0.69222589,         nan,  0.69956897,  0.73090384],
       [ 0.78023728,  0.69642475,  0.81255486,  0.69780407,  0.69224877],
       [        nan, -1.        ,  0.69239057,  0.69254709,  0.80751116],
       [        nan,  0.83073524,         nan,  0.75698294,  0.79615312]])

In [270]:
z < - z

array([[False, False, False, False, False],
       [ True, False,  True, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False],
       [ True, False,  True, False, False]])

In [271]:
z/1/1

array([[ 0.06507691,  0.01383003,  0.        ,  0.71938148,  0.54107592],
       [-0.90541162,  0.37307378, -0.89681711,  0.28321998,  0.5853674 ],
       [ 0.11451288,  0.43678313,  0.76137674,  0.29359672,  0.36074929],
       [-0.98131022, -1.        ,  0.35376309,  0.38723334,  0.75274894],
       [-0.98867932,  0.06957645, -0.91270967,  0.65279042,  0.73258362]])

In [275]:
z > z

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [281]:
np.array(0) // np.array(0)

/Users/manpreetsi/opt/anaconda3/envs/deeplearning_practise/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [283]:
np.array(0) // np.array(0.)

nan

In [284]:
np.array(0) / np.array(0)

/Users/manpreetsi/opt/anaconda3/envs/deeplearning_practise/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [289]:
6//2, 6/2

(3, 3.0)

In [291]:
z = np.zeros((5,5))
z = z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [296]:
z = np.random.random(10)
z.sort()
print(z)

[0.05758774 0.33444263 0.48580761 0.54152196 0.81503671 0.83195287
 0.9225376  0.9272425  0.93479034 0.93910221]


In [324]:
z=np.random.random((4,4))
z.sort()
print(z)

[[0.01739416 0.44402204 0.45427639 0.49091379]
 [0.13357396 0.22049725 0.62781985 0.78427081]
 [0.01333794 0.21933069 0.45127853 0.49639229]
 [0.37790104 0.65997478 0.87879022 0.94631846]]


In [325]:
z= np.random.randint(1,10,(3,3))
z.sort() ## Row level sorting
print(z)

[[2 3 3]
 [1 3 3]
 [4 8 9]]


In [326]:
np.allclose(z,z) ## Check all elements of two arrays are equal or not

True

#### get max, min, mean etc. of an array column and row wise

In [327]:
np.min(z) , np.max(z), np.sum(z) ,np.mean(z), np.median(z) ## min, max, sum, mean, median

(1, 9, 36, 4.0, 3.0)

In [331]:
z.min(), z.max(), z.sum() ,z.mean()

(1, 9, 36, 4.0)

In [333]:
z.min(axis=1), z.max(axis=1),z.sum(axis=1), z.mean(axis=1) ## Row Level

(array([2, 1, 4]),
 array([3, 3, 9]),
 array([ 8,  7, 21]),
 array([2.66666667, 2.33333333, 7.        ]))

In [334]:
z.min(axis=0), z.max(axis=0),z.sum(axis=0), z.mean(axis=0) ## Column Level

(array([1, 3, 3]),
 array([4, 8, 9]),
 array([ 7, 14, 15]),
 array([2.33333333, 4.66666667, 5.        ]))

In [312]:
a = np.random.randint(1,100,(3,3))
print(a)
b = np.random.randint(1,100,(3,3))
print(b)

[[53 88 52]
 [41 48 97]
 [56 86 17]]
[[94 87 68]
 [13  6 90]
 [46 20 27]]


In [316]:
a + b , a*b , a/b

(array([[147, 175, 120],
        [ 54,  54, 187],
        [102, 106,  44]]),
 array([[4982, 7656, 3536],
        [ 533,  288, 8730],
        [2576, 1720,  459]]),
 array([[0.56382979, 1.01149425, 0.76470588],
        [3.15384615, 8.        , 1.07777778],
        [1.2173913 , 4.3       , 0.62962963]]),
 array([[ 8518,  6179, 12928],
        [ 8940,  5795,  9727],
        [ 7164,  5728, 12007]]))

#### change data type of array elements

In [321]:
z = np.arange(9,dtype=np.int32)
print(z)
z = z.astype(np.float32,copy=False)
print(z)

[0 1 2 3 4 5 6 7 8]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [341]:
z= np.random.randint(1,10,(3,3))
z.sort() ## Row level sorting
print(z)

array([[2, 3, 3],
       [1, 3, 3],
       [4, 8, 9]])

In [339]:
z - z.mean(axis=1,keepdims=True)

(array([[-0.66666667,  0.33333333,  0.33333333],
        [-1.33333333,  0.66666667,  0.66666667],
        [-3.        ,  1.        ,  2.        ]]),)

In [340]:
z - z.mean(axis=1)

array([[-0.66666667,  0.66666667, -4.        ],
       [-1.66666667,  0.66666667, -4.        ],
       [ 1.33333333,  5.66666667,  2.        ]])

In [477]:
~z.any(axis=0).any()

False

#### Check null/nan values in an array 

In [476]:
np.isnan(z).any()

False

In [348]:
np.diag(np.dot(a,b))

array([ 8518,  5795, 12007])

In [356]:
a, a[[0,1,2]]

(array([[53, 88, 52],
        [41, 48, 97],
        [56, 86, 17]]),
 array([[53, 88, 52],
        [41, 48, 97],
        [56, 86, 17]]))

#### Get power of a number in numpy

In [358]:
c = 2
np.power(c,3)

8

In [362]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [368]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [369]:
c = np.arange(10)

#### get array values based on a condition - Replace values

In [384]:
d=[c[i] for i in range(len(c)) if c[i]%2!=0]
d

[1, 3, 5, 7, 9]

In [382]:
c[c%2 !=0]

array([1, 3, 5, 7, 9])

In [393]:
c[c%2!=0]=-1
c

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [394]:
arr = np.arange(10)

#### get array values based on a condition - create a new array  (np.where)

In [398]:
output = np.where(arr%2!=0,-1,arr) ## create a new array where all values that are odd are replaced with -1

In [399]:
output

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Reshaping an array

In [403]:
output.reshape(2,-1) ## Setting -1 decides the number of columns

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [404]:
output.reshape(-1,2) ## Setting -1 decides the number of rows

array([[ 0, -1],
       [ 2, -1],
       [ 4, -1],
       [ 6, -1],
       [ 8, -1]])

In [406]:
a,b

(array([[53, 88, 52],
        [41, 48, 97],
        [56, 86, 17]]),
 array([[94, 87, 68],
        [13,  6, 90],
        [46, 20, 27]]))

#### Differrnt ways to concatenate - horizantally and vertically

In [417]:
print(f"{np.concatenate([a,b])} \n\n {np.concatenate([a,b],axis=0)} \n\n {np.concatenate([a,b],axis=1)}")

[[53 88 52]
 [41 48 97]
 [56 86 17]
 [94 87 68]
 [13  6 90]
 [46 20 27]] 

 [[53 88 52]
 [41 48 97]
 [56 86 17]
 [94 87 68]
 [13  6 90]
 [46 20 27]] 

 [[53 88 52 94 87 68]
 [41 48 97 13  6 90]
 [56 86 17 46 20 27]]


In [421]:
np.vstack([a,b]), np.hstack([a,b])

(array([[53, 88, 52],
        [41, 48, 97],
        [56, 86, 17],
        [94, 87, 68],
        [13,  6, 90],
        [46, 20, 27]]),
 array([[53, 88, 52, 94, 87, 68],
        [41, 48, 97, 13,  6, 90],
        [56, 86, 17, 46, 20, 27]]))

In [441]:
g = np.array([2,1,3,4,5,6,7,8,9,10])
h = np.array([2,4,6,8,10])
g,h

(array([ 2,  1,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 2,  4,  6,  8, 10]))

#### Find ommon values between 2 arrays

In [442]:
np.intersect1d(g,h)

array([ 2,  4,  6,  8, 10])

In [443]:
np.setdiff1d(g,h)

array([1, 3, 5, 7, 9])

In [444]:
index=np.where(g==h)
index

/Users/manpreetsi/opt/anaconda3/envs/deeplearning_practise/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


(array([], dtype=int64),)

#### Get index value based on conditons - np.where

In [451]:
index = np.where(g%3==0)
index,

((array([2, 5, 8]),),)

In [452]:
g[index]

array([3, 6, 9])

In [472]:
a

array([[52, 53, 88],
       [41, 48, 97],
       [17, 56, 86]])

#### Different ways to sort an array

In [455]:
a.sort()
a

array([[52, 53, 88],
       [41, 48, 97],
       [17, 56, 86]])

In [468]:
np.sort(a)

array([[52, 53, 88],
       [41, 48, 97],
       [17, 56, 86]])

In [470]:
np.sort(a,axis=0) ## Column wise sorting

array([[17, 48, 86],
       [41, 53, 88],
       [52, 56, 97]])

In [471]:
np.sort(a,axis=1) ## Row wise sorting

array([[52, 53, 88],
       [41, 48, 97],
       [17, 56, 86]])

In [458]:
a[::-1], a[:,::-1]

(array([[17, 56, 86],
        [41, 48, 97],
        [52, 53, 88]]),
 array([[88, 53, 52],
        [97, 48, 41],
        [86, 56, 17]]))

#### Check nan values and replace nan values

In [460]:
np.isnan(a).any()

False

In [461]:
a[np.isnan(a)]=0 ## Replace na with 0

In [474]:
np.unique(np.sort(a))[-2]

88

In [502]:
a[~np.isnan(a)].reshape(3,-1) ## Drop na and get rest of the array in an array having 3 rows and x columns

array([[52, 53, 88],
       [41, 48, 97],
       [17, 56, 86]])

#### Euclidian distance

In [503]:
np.linalg.norm(a-b) ## Euclidian distance

107.4011173126239

# pandas Operations

In [7]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.1.0'

In [6]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
df = pd.DataFrame(np.random.random((3,3)), index = ['A','B','C'])
df

0         1         2
A  0.467895  0.503825  0.061421
B  0.933716  0.625193  0.053711
C  0.890943  0.986183  0.502371

In [ ]:
## Dict to Dataframe

In [113]:
mydict = ({
                'A': 1.,
                'B' : pd.Timestamp('20130102'),
                'C' : pd.Series([1,2,3,4],dtype='float32'),
                'D' : np.array([3]*4,dtype='int32'),
                'E' : pd.Categorical(['test','train','test','train'])
})

In [114]:
mydf = pd.DataFrame(mydict)
mydf

A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  2.0  3  train
2  1.0 2013-01-02  3.0  3   test
3  1.0 2013-01-02  4.0  3  train

In [21]:
mydf.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
dtype: object

In [22]:
type(mydf)

pandas.core.frame.DataFrame

In [24]:
## df.<TAB>  -- To get hints
sum(df.isna().any())

0

In [26]:
mydf.head(2)

A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  2.0  3  train

In [29]:
mydf.tail(2)

A          B    C  D      E
2  1.0 2013-01-02  3.0  3   test
3  1.0 2013-01-02  4.0  3  train

In [30]:
mydf.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
mydf.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [32]:
mydf.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 2.0, 3, 'train'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 3.0, 3, 'test'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 4.0, 3, 'train']],
      dtype=object)

In [33]:
mydf.describe()

A         C    D
count  4.0  4.000000  4.0
mean   1.0  2.500000  3.0
std    0.0  1.290994  0.0
min    1.0  1.000000  3.0
25%    1.0  1.750000  3.0
50%    1.0  2.500000  3.0
75%    1.0  3.250000  3.0
max    1.0  4.000000  3.0

In [34]:
mydf.T

0                    1                    2  \
A                    1                    1                    1   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                    1                    2                    3   
D                    3                    3                    3   
E                 test                train                 test   

                     3  
A                    1  
B  2013-01-02 00:00:00  
C                    4  
D                    3  
E                train

In [55]:
mydf.sort_values(by='E',ascending=True,inplace=True)
mydf.index = range(len(mydf))
mydf

A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  3.0  3   test
2  1.0 2013-01-02  2.0  3  train
3  1.0 2013-01-02  4.0  3  train

### SELECTING data from a Dataframe

In [ ]:
'''

Note: While standard Python / Numpy expressions for selecting and setting are intuitive and
come in handy for interactive work, for production code, we recommend the optimized pandas
data access methods, .at, .iat, .loc, .iloc and .ix

'''

#### Getting

In [56]:
mydf['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [57]:
mydf[0:1]

A          B    C  D     E
0  1.0 2013-01-02  1.0  3  test

#### Selection by Label       ->     .loc  / .at

In [60]:
mydf.loc[:,['A','E']] ## Select all rows but only A and E column

A      E
0  1.0   test
1  1.0   test
2  1.0  train
3  1.0  train

In [65]:
mydf.loc[2:2,['A','C','E']] ## or mydf.loc[]'2':'2',['A','C','E']] as .loc takes index value and not index number

A    C      E
2  1.0  2.0  train

In [71]:
mydf.loc[2,'A']

1.0

In [72]:
mydf.at[2,'A'] ## This is faster the former one, but for only one particular value(row) only

1.0

#### Selection by Position ->  iloc / .iat

In [82]:
mydf.iloc[0:1,0:3]

A          B    C
0  1.0 2013-01-02  1.0

In [84]:
mydf.iloc[[0,3],[1,4]]

B      E
0 2013-01-02   test
3 2013-01-02  train

In [85]:
mydf.iloc[0,0]

1.0

In [86]:
mydf.iat[0,0]

1.0

#### Boolean indexing | Filtering

In [265]:
mydf[mydf.C > 2]['A']

3    1.0
4    1.0
Name: A, dtype: float64

In [ ]:
#### Create a DataFrame after agg. operation on a Dataframe

In [287]:
lst = []
lst = mydf[mydf.C > 2]['A'].mean()

In [395]:
lst

1.0

In [288]:
## This will through error

mydataframe = pd.DataFrame(lst) 

ValueError: DataFrame constructor not properly called!

In [295]:
## Solution :- 
lst = mydf[mydf.C > 2]['A'].mean()
lst.tolist() ## numpy.float64 converted to numpy
mylist = [] ## new list created
mylist.append(lst) ## Data Appended
mydataframe = pd.DataFrame(mylist,columns=['x'])  ## DataFrame created from a List

In [296]:
mydataframe

x
0  1.0

In [88]:
## isin() filtering

In [97]:
mydf[(mydf.E == 'test') | (mydf.E=='train')] ## or(|) / and(&) operation

A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  3.0  3   test
2  1.0 2013-01-02  2.0  3  train
3  1.0 2013-01-02  4.0  3  train

In [98]:
mydf[mydf['E'].isin(['test','train'])] ## isin operation

A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  3.0  3   test
2  1.0 2013-01-02  2.0  3  train
3  1.0 2013-01-02  4.0  3  train

In [99]:
#Adding a new column from List or pd.Series

In [115]:
l1 = ['L1','L2','L3','L4']
series = pd.Series(['S1','S2','S3','S3'])

In [116]:
mydf['list']= l1
mydf['series']=series

In [117]:
mydf

A          B    C  D      E list series
0  1.0 2013-01-02  1.0  3   test   L1     S1
1  1.0 2013-01-02  2.0  3  train   L2     S2
2  1.0 2013-01-02  3.0  3   test   L3     S3
3  1.0 2013-01-02  4.0  3  train   L4     S3

In [104]:
mydf[mydf.A>1]

Empty DataFrame
Columns: [A, B, C, D, E, list, series]
Index: []

#### Treat Missing Data

In [123]:
## Reindexing allows you to change/add/delete the index on a specified axis.

mydf = mydf.reindex(index = range(1,len(mydf)+1), columns = list(mydf.columns)) 
## Way 1 -- This will not include 0th row 

In [126]:
mydf.index = range(1,len(mydf)+1) ## Way 2 (I like this)

In [127]:
mydf

A          B    C  D      E list series
1  1.0 2013-01-02  1.0  3   test   L1     S1
2  1.0 2013-01-02  2.0  3  train   L2     S2
3  1.0 2013-01-02  3.0  3   test   L3     S3
4  1.0 2013-01-02  4.0  3  train   L4     S3

In [128]:
## Drop any row that has missing value in it (in any column)

mydf.dropna(how='any',inplace=True)

In [129]:
## Drop any row of column 'A' which has null/na value

mydf['A'].dropna(how='any',inplace=True)

In [ ]:
## Fill na of any row with value = 5

mydf.fillna(value = 5,inplace=True )

In [131]:
## Fill na of column A which has na value with value = 5

mydf['A'].fillna(value=5,inplace=True)

In [132]:
mydf

A          B    C  D      E list series
1  1.0 2013-01-02  1.0  3   test   L1     S1
2  1.0 2013-01-02  2.0  3  train   L2     S2
3  1.0 2013-01-02  3.0  3   test   L3     S3
4  1.0 2013-01-02  4.0  3  train   L4     S3

In [ ]:
## Fill na of column 'A' with mean value of A 

mydf['A'].fillna(value = mydf['A'].mean())

In [138]:
mydf.isnull(), mydf.isna()

(       A      B      C      D      E   list  series
 1  False  False  False  False  False  False   False
 2  False  False  False  False  False  False   False
 3  False  False  False  False  False  False   False
 4  False  False  False  False  False  False   False,
        A      B      C      D      E   list  series
 1  False  False  False  False  False  False   False
 2  False  False  False  False  False  False   False
 3  False  False  False  False  False  False   False
 4  False  False  False  False  False  False   False)

In [139]:
mydf.isna().any()

A         False
B         False
C         False
D         False
E         False
list      False
series    False
dtype: bool

In [140]:
sum(mydf.isna().any())

0

### Operations

In [143]:
## Mean Median 

mydf['A'].mean(), mydf['A'].median()

(1.0, 1.0)

In [144]:
mydf

A          B    C  D      E list series
1  1.0 2013-01-02  1.0  3   test   L1     S1
2  1.0 2013-01-02  2.0  3  train   L2     S2
3  1.0 2013-01-02  3.0  3   test   L3     S3
4  1.0 2013-01-02  4.0  3  train   L4     S3

#### Apply Function

In [153]:
mydf['C'] =  mydf['C'].apply(lambda x : x*2)

In [154]:
mydf

A          B  C  D      E list series
1  1.0 2013-01-02  2  3   test   L1     S1
2  1.0 2013-01-02  4  3  train   L2     S2
3  1.0 2013-01-02  6  3   test   L3     S3
4  1.0 2013-01-02  8  3  train   L4     S3

In [155]:
mydf['C'] = mydf['C'].apply(lambda x : x if x > 3  else 0 )

In [156]:
mydf

A          B  C  D      E list series
1  1.0 2013-01-02  0  3   test   L1     S1
2  1.0 2013-01-02  4  3  train   L2     S2
3  1.0 2013-01-02  6  3   test   L3     S3
4  1.0 2013-01-02  8  3  train   L4     S3

In [169]:
### .loc gives onky 1 operation at a time unlike apply  or map-apply

mydf.loc[mydf.E=='test','loc']='Test it is ' 

In [170]:
mydf

A          B  C  D      E list series          loc
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

#### Apply with Map

In [163]:
## map gives a object, so we need list data type to retrieve the value
## map (function, input_value)

mydf['C'] = list(map(lambda x : x if x >=5 else 0, mydf['C'])) 

In [177]:
mydf

A          B  C  D      E list series          loc
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

#### Get total unique values of a column and their count 

In [165]:

mydf['E'].value_counts()

train    2
test     2
Name: E, dtype: int64

#### String Method 

In [168]:
mydf['series'].str.lower()

1    s1
2    s2
3    s3
4    s3
Name: series, dtype: object

#### merge 2 or more dataframes !

In [178]:
## To concat two dataframes row wise - Horizontally ; default axis = 0

pd.concat([mydf,mydf],axis =0 ) 

A          B  C  D      E list series          loc
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

In [179]:
## To concat dataframes column wise - Vertically
pd.concat([mydf,mydf],axis=1)

A          B  C  D      E list series          loc    A          B  C  D  \
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is   1.0 2013-01-02  0  3   
2  1.0 2013-01-02  0  3  train   L2     S2          NaN  1.0 2013-01-02  0  3   
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is   1.0 2013-01-02  6  3   
4  1.0 2013-01-02  8  3  train   L4     S3          NaN  1.0 2013-01-02  8  3   

       E list series          loc  
1   test   L1     S1  Test it is   
2  train   L2     S2          NaN  
3   test   L3     S3  Test it is   
4  train   L4     S3          NaN

In [898]:
## To join dataframes like in SQL  - Merge

pd.merge(mydf,mydf,on='series', how = 'left')

A_x        B_x  C_x  D_x    E_x list_x series        loc_x         F_x  \
0  1.0 2013-01-02    0    3   test     L1     S1  Test it is   validation   
1  1.0 2013-01-02    0    3  train     L2     S2          NaN       train   
2  1.0 2013-01-02    6    3   test     L3     S3  Test it is   validation   
3  1.0 2013-01-02    6    3   test     L3     S3  Test it is   validation   
4  1.0 2013-01-02    8    3  train     L4     S3          NaN       train   
5  1.0 2013-01-02    8    3  train     L4     S3          NaN       train   

          G_x  A_y        B_y  C_y  D_y    E_y list_y        loc_y  \
0  validation  1.0 2013-01-02    0    3   test     L1  Test it is    
1       train  1.0 2013-01-02    0    3  train     L2          NaN   
2  validation  1.0 2013-01-02    6    3   test     L3  Test it is    
3  validation  1.0 2013-01-02    8    3  train     L4          NaN   
4       train  1.0 2013-01-02    6    3   test     L3  Test it is    
5       train  1.0 2013-01-02    8    3  train     L4          NaN   

          F_y         G_y  
0  validation  validation  
1       train       train  
2  validation  validation  
3       train       train  
4  validation  validation  
5       train       train

In [184]:
pd.merge(mydf[['A','B','series']],mydf[['C','D','series']], on = 'series')

A          B series  C  D
0  1.0 2013-01-02     S1  0  3
1  1.0 2013-01-02     S2  0  3
2  1.0 2013-01-02     S3  6  3
3  1.0 2013-01-02     S3  8  3
4  1.0 2013-01-02     S3  6  3
5  1.0 2013-01-02     S3  8  3

In [ ]:
#### Append 

In [191]:
s = mydf.iloc[3:,:]
s

A          B  C  D      E list series  loc
4  1.0 2013-01-02  8  3  train   L4     S3  NaN

In [192]:
mydf.append(s,ignore_index=True)
##mydf = mydf.append(s,ignore_index=True) to save it in mydf after append

A          B  C  D      E list series          loc
0  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
1  1.0 2013-01-02  0  3  train   L2     S2          NaN
2  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
3  1.0 2013-01-02  8  3  train   L4     S3          NaN
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

In [226]:
mydf

A          B  C  D      E list series          loc
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

#### Grouping

In [194]:
mydf.groupby('series')['A'].sum()

series
S1    1.0
S2    1.0
S3    2.0
Name: A, dtype: float64

In [195]:
## Grouping by multiple columns forms a hierarchical index

mydf.groupby(['series','E'])['C'].sum()

series  E    
S1      test     0.0
        train    NaN
S2      test     NaN
        train    0.0
S3      test     6.0
        train    8.0
Name: C, dtype: float64

In [227]:
mydf.groupby('E')['C'].size()

E
test     2
train    2
Name: C, dtype: int64

#### Pivot Tables

In [2]:
import pandas as pd
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",

                         "bar", "bar", "bar", "bar"],

                   "B": ["one", "one", "one", "two", "two",

                         "one", "one", "two", "two"],

                   "C": ["small", "large", "large", "small",

                         "small", "large", "small", "small",

                         "large"],

                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],

                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [3]:
df.sort_values(by = ['A','B','C','D','E'], ascending = True,inplace=True)
df.index = range(len(df))
df

A    B      C  D  E
0  bar  one  large  4  6
1  bar  one  small  5  8
2  bar  two  large  7  9
3  bar  two  small  6  9
4  foo  one  large  2  4
5  foo  one  large  2  5
6  foo  one  small  1  2
7  foo  two  small  3  5
8  foo  two  small  3  6

In [ ]:
'''
pd.pivot_table(dataframe_name, index,columns,values,aggfunc)

index = Row names
Columns = Columns from the data
Values = Values in each cell for selected Index and Columns
Agg_func = To be applied on values (Sum, count, min etc.)

'''

In [7]:
## Count with custom agg function using lambda

pd.pivot_table(df, index = ['A','C'], columns=['B'], values = ['D'], aggfunc= lambda x : len(x),dropna=True)

D     
B          one  two
A   C              
bar large  1.0  1.0
    small  1.0  1.0
foo large  2.0  NaN
    small  1.0  2.0

In [233]:
## Count with inbuilt agg function - np.size

pd.pivot_table(df,index = ['A','C'], columns = ['B'], values=['D'], aggfunc =np.size)

D     
B          one  two
A   C              
bar large  1.0  1.0
    small  1.0  1.0
foo large  2.0  NaN
    small  1.0  2.0

In [216]:
## Count Distinct with custom agg function using lambda

pd.pivot_table(df, index = ['A','C'], columns=['B'], values = ['D'], 
               aggfunc= lambda x : len(x.dropna().unique()),dropna=True)


D     
B          one  two
A   C              
bar large  1.0  1.0
    small  1.0  1.0
foo large  1.0  NaN
    small  1.0  1.0

In [220]:
## Np.sum vs lambda sum

##lambda sum
pd.pivot_table(df, index = ['A','C'], columns=['B'], values = ['D','E'], 
               aggfunc= lambda x : sum(x),dropna=True)


D         E      
B          one  two  one   two
A   C                         
bar large  4.0  7.0  6.0   9.0
    small  5.0  6.0  8.0   9.0
foo large  4.0  NaN  9.0   NaN
    small  1.0  6.0  2.0  11.0

In [230]:

## np.sum()
pd.pivot_table(df, index = ['A','C'], columns=['B'], values = ['D'], 
               aggfunc= np.sum,dropna=True)


D     
B          one  two
A   C              
bar large  1.0  1.0
    small  1.0  1.0
foo large  2.0  NaN
    small  1.0  2.0

#### categroicals

In [242]:
df

A    B      C  D  E
0  bar  one  large  4  6
1  bar  one  small  5  8
2  bar  two  large  7  9
3  bar  two  small  6  9
4  foo  one  large  2  4
5  foo  one  large  2  5
6  foo  one  small  1  2
7  foo  two  small  3  5
8  foo  two  small  3  6

In [249]:
df['B'] ## dtype is object

0    one
1    one
2    two
3    two
4    one
5    one
6    one
7    two
8    two
Name: B, dtype: object

In [250]:
df['B']= df['B'].astype('category')

In [251]:
df['B'] ## dtype is category

0    one
1    one
2    two
3    two
4    one
5    one
6    one
7    two
8    two
Name: B, dtype: category
Categories (2, object): ['one', 'two']

In [252]:
## Rename the categories :- 

df['B'].cat.categories = ['Cat_One','Cat_Two']

In [253]:
df['B']

0    Cat_One
1    Cat_One
2    Cat_Two
3    Cat_Two
4    Cat_One
5    Cat_One
6    Cat_One
7    Cat_Two
8    Cat_Two
Name: B, dtype: category
Categories (2, object): ['Cat_One', 'Cat_Two']

# Lambda, Map, Reduce, Filter, List Comprehension, applymap

## Lambda

In [ ]:
## 1. In a lambda function, statements like return, pass, assert, or raise will raise a SyntaxError exception.
## 2. lambda expression can be anonymous,you don’t even need to assign it to a name.

In [255]:
mult = lambda x : x*2;
print(mult(2))

4


#### Function in Lambda 

In [297]:
myfunc = lambda x, func : x*func(x)

In [298]:
myfunc(2, lambda x:x*2)

8

#### Send Multiple Argument using *args

In [306]:
mult_mult = (lambda *args: args[1])

In [308]:
mult_mult(1,2,3)

2

In [312]:
(lambda *args : sum(args))(1,2,3,4)

10

#### List comprehension inside Lambda

In [317]:
mylambda = lambda x : [i for i in range(len(x)) if i >4]

In [318]:
mylambda([1,2,3,4,5,6,7])

[5, 6]

#### if else in Lambda

In [336]:
## There is no direct way to use elif but we can use it using else (if else)

(lambda x,y : x*y if x >2 else y)(2,6)

6

#### Lambda on DataFrame for parallel computation

In [337]:
mydf

A          B  C  D      E list series          loc
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is 
2  1.0 2013-01-02  0  3  train   L2     S2          NaN
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is 
4  1.0 2013-01-02  8  3  train   L4     S3          NaN

In [338]:
mydf['F']=mydf['E'].apply(lambda x : x if x == 'train' else 'validation')

In [339]:
mydf

A          B  C  D      E list series          loc           F
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is   validation
2  1.0 2013-01-02  0  3  train   L2     S2          NaN       train
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is   validation
4  1.0 2013-01-02  8  3  train   L4     S3          NaN       train

## Map

In [ ]:
'''
Map applies a function to all the items in an input_list. Here is the blueprint:

map(function_to_apply, list_of_inputs)     -- IMPORTANT { map syntax }
-- The first argument is the name of a function 
-- The second argument is iterable: an iterable object (e.g. list, tuple, dictionary).


In [363]:
list(map(lambda x :x , 2)) ## as int is not an iterable object

TypeError: 'int' object is not iterable

In [340]:
map_object = map(lambda x : x*2, [1,2,3,4,5])

In [341]:
map_object

In [342]:
list(map_object)

[2, 4, 6, 8, 10]

#### Map + lambda on DataFrame

In [343]:
mydf

A          B  C  D      E list series          loc           F
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is   validation
2  1.0 2013-01-02  0  3  train   L2     S2          NaN       train
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is   validation
4  1.0 2013-01-02  8  3  train   L4     S3          NaN       train

In [344]:
mydf['G'] = list(map(lambda x : x if x == 'train' else 'validation',mydf['E'] ))

In [345]:
mydf

A          B  C  D      E list series          loc           F  \
1  1.0 2013-01-02  0  3   test   L1     S1  Test it is   validation   
2  1.0 2013-01-02  0  3  train   L2     S2          NaN       train   
3  1.0 2013-01-02  6  3   test   L3     S3  Test it is   validation   
4  1.0 2013-01-02  8  3  train   L4     S3          NaN       train   

            G  
1  validation  
2       train  
3  validation  
4       train

## Filter

In [ ]:
'''
filter creates a list of elements for which a function returns true
'''

In [351]:
list(filter(lambda x : x>3,[1,2,3,4,5])) ## return elementa from the input list that are greater than 3

[4, 5]

In [353]:
list(map(lambda x : x>3, [1,2,3,4,5] ))

[False, False, False, True, True]

In [354]:
list(map(lambda x : x if x>3 else 0, [1,2,3,4,5]))

[0, 0, 0, 4, 5]

In [352]:
df

A        B      C  D  E
0  bar  Cat_One  large  4  6
1  bar  Cat_One  small  5  8
2  bar  Cat_Two  large  7  9
3  bar  Cat_Two  small  6  9
4  foo  Cat_One  large  2  4
5  foo  Cat_One  large  2  5
6  foo  Cat_One  small  1  2
7  foo  Cat_Two  small  3  5
8  foo  Cat_Two  small  3  6

### Map v/s Filter

In [ ]:
## Map is used to perform an operation based on a condition in a list input
## Filter is used to filter out the elements that are true on the givencondition for a list input

In [355]:
def square(x):
    return list(map(lambda y : y**2, x))

In [356]:
def square_root(x):
    return list(map(lambda y : round(y**(1/2), x))

In [357]:
func_list = [square, square_root]

In [358]:
my_input= [1,2,3,2,5,7]

In [359]:
val = list(map(lambda x : x(list(filter(lambda x : x >2,my_input))), func_list))

In [362]:
val

[[9, 25, 49], [1.7320508075688772, 2.23606797749979, 2.6457513110645907]]

## Reduce

In [ ]:
'''

History and General infromation about reduce :- https://realpython.com/python-reduce-function/

Syntax :- 

reduce(function(x,y),iterable,initializer=None)   ##function should have two arguments. 

FYI :- 
Even though the official documentation refers to the first argument of reduce() as “a function of two arguments,” 
you can pass any Python callable to reduce() as long as the callable accepts two arguments. 
Callable objects include classes, instances that implement a special method called __call__(), 
instance methods, class methods, static methods, and functions.

Processing/working of reduce :-
reduce does a cumulative operation on all the iterables taking 2 at a time, to return a single value


'''


In [366]:
from functools import reduce

In [376]:
iter_obj = iter([1,2,3,4,5])

In [377]:
next(iter_obj)

1

In [380]:
my_input

[1, 2, 3, 2, 5, 7]

In [387]:
## Background operation :- 1/2/3/4/5/7

my_sum = functools.reduce(lambda x,y : x/y, my_input) 
print(my_sum)

0.0023809523809523807


In [386]:
## Background operation :- ((1/2*1)/3*(1/2*1))/4*((1/2*1)/3*(1/2*1))

my_sum = functools.reduce(lambda x,y : x/y*x, [1,2,3,4]) 
print(my_sum)

0.001736111111111111


In [381]:
## Background operation :- 100/1/2/3/4/5/7 as 100 is the initializer

my_sum = functools.reduce(lambda x,y : x/y, my_input,100) 
print(my_sum)

0.2380952380952381


#### Find maximum and minimum in a list using reduce i.e without using in-built min and max function of a list

In [392]:
my_input

[1, 2, 3, 2, 5, 7]

In [390]:
min_num = reduce(lambda x,y : x if x < y else y, my_input)
min_num

1

In [391]:
max_num = reduce(lambda x,y : x if x >y else y, my_input)
max_num

7

## List Comprehension

In [ ]:
### Faster and simpler than map, reduce, and filter.

#### map vs list comprehension

In [397]:
list(map(lambda x : x*2, [1,2,3,4,5]))

[2, 4, 6, 8, 10]

In [400]:
[x*2 for x in [1,2,3,4,5]]

[2, 4, 6, 8, 10]

#### filter vs list comprehension

In [401]:
list(filter(lambda x : x>2,[1,2,3,4,5]))

[3, 4, 5]

#### if condition

In [413]:
[x for x in [1,2,3,4,5] if x >2]

[3, 4, 5]

#### if-else loop condition

In [418]:
## Way 1 

[x if x < 2 else ( 0 if x ==3 else x) for x in [1,2,3,4,5] ]

[1, 2, 0, 4, 5]

In [530]:
## Way 2

[x if x<2   else 0 if x==3   else x for x in [1,2,3,4,5]]

[1, 2, 0, 4, 5]

#### Nested if condition

In [426]:
[x for x in [1,2,3,4,5] if x>2 if x%4==0]

[4]

#### Nested List

In [430]:
[[i*j for i in [1,2,3]] for j in [1,2]]

[[1, 2, 3], [2, 4, 6]]

#### list comprehension with dict = Dict Comprehension

In [419]:
[x for x in {1,2,3,4}]

[1, 2, 3, 4]

In [455]:
mydict = {
    'Name': ['Sahil','Mahima'],
    'Age':[28,27],
    'sex':['M','F']
    
}

In [522]:
type(mydict.values())

dict_values

In [523]:
type(mydict.keys())

dict_keys

In [449]:
{key:value for (key,value) in mydict.items()}

{'Name': ['Sahil', 'Mahima'], 'Age': [28, 27], 'sex': ['M', 'F']}

In [520]:
type(mydict['Age'])

list

In [521]:
type(mydict['Age'][0])

int

In [880]:
type(mydict['Age'][0]) == int

True

In [882]:
isinstance(mydict['Age'][0],int)

True

In [881]:
{key:value*2  for (key,value) in mydict.items() if isinstance(value,int)} 
## no ouput, as value here is a list i.e [28,27] and not an indivdual values i.e 28,27

{}

In [884]:
## Solution

## Way 1
'''
for y in mydict.keys():
    for i in mydict[y]:
        if isinstance(i,int):
            print(i*2)
        else:
            print(i)
'''

[[ i*2 if type(i)==int else i for i in mydict[y]] for y in mydict.keys()]

##or 
## [[ i*2 if isinstance(i,int)else i for i in mydict[y]] for y in mydict.keys()]

[['Sahil', 'Mahima'], [56, 54], ['M', 'F']]

In [529]:
## Way 2

'''
for y in mydict.keys():
    for i in mydict[y]:
        if isinstance(i,int)==False:
            print(i)
        elif isinstance(i,int)==True:
            print(i*2)
        else :
            None
'''


[[ i if isinstance(i,int)==False else i*2 if isinstance(i,int) else None for i in mydict[y]] for y in mydict.keys()]

[['Sahil', 'Mahima'], [56, 54], ['M', 'F']]

In [553]:
'''
for y in mydict.keys():
    for i in mydict[y]:
        if isinstance(i,int):
            if(i==27):
                print(i*2)
            else :
                print(i)
        else:
            print(i)
'''

[[i*2 for i in mydict[y] if isinstance(i,int) if i==27 else i if i!=27 else i ] for y in mydict.keys()]

SyntaxError: invalid syntax (<ipython-input-553-42f85f8efc24>, line 13)

In [452]:
pd.DataFrame({key:value for (key,value) in mydict.items()})

Name  Age sex
0   Sahil   28   M
1  Mahima   27   F

In [453]:
mydict.items()

dict_items([('Name', ['Sahil', 'Mahima']), ('Age', [28, 27]), ('sex', ['M', 'F'])])

In [454]:
pd.DataFrame(mydict)

Name  Age sex
0   Sahil   28   M
1  Mahima   27   F

In [549]:
dict1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f':6}

# Identify odd and even entries
dict1_tripleCond = {k:('even' if v%2==0 else 'odd') for (k,v) in dict1.items()}

print(dict1_tripleCond)

{'a': 'odd', 'b': 'even', 'c': 'odd', 'd': 'even', 'e': 'odd', 'f': 'even'}


## applymap

In [ ]:
## Apply a function to a Dataframe elementwise.
## wherewas apply is used on pd series and not whole dataframe

In [558]:
df.head(4)

A        B      C  D  E
0  bar  Cat_One  large  4  6
1  bar  Cat_One  small  5  8
2  bar  Cat_Two  large  7  9
3  bar  Cat_Two  small  6  9

In [559]:
df.applymap(lambda x : str(x) + '_X').head(4)

A          B        C    D    E
0  bar_X  Cat_One_X  large_X  4_X  6_X
1  bar_X  Cat_One_X  small_X  5_X  8_X
2  bar_X  Cat_Two_X  large_X  7_X  9_X
3  bar_X  Cat_Two_X  small_X  6_X  9_X

# Loops and conditionals

### For loop

### For loop + if-else

In [857]:
num1 = int(34)
num2 = int(45)
cnt = 0
for i in list(np.arange(num1+1,num2)):
    for j in range(2,i):
        if i%j==0:
            break;
    else:
        print(i)


37
41
43


### While loop

In [849]:
i=0 
while i < 2:
    print("Hello")
    i+=1

Hello
Hello


### While Loop + if-else

In [ ]:
# The else clause is only executed when your while condition becomes false. 
#If you break out of the loop, or if an exception is raised, it won’t be executed.

In [850]:
i =4
while i > 2 :
    print("Hello")
    i -=1
else :
    print("out of loop now")

Hello
Hello
out of loop now


#### Use of Pass

In [ ]:
# Pass Statement: 
# We use pass statement to write empty loops. Pass is also used for empty control statement, function and classes. 


# Classes Object and Self

### Example 1.1 (Where you can access variables of a class or class function through its object)

In [36]:
class VmwFutureWork():
    def __init__(self):
        self.cities = ['Delhi','Mumbai','Bangalore','Hyderabad'];
        print(f"New Object Created: {self}")
    
    def work_location(self,loc,comp):
        self.loc,self.comp=loc,comp;
        
        if self.loc in self.cities:
            return("Hurray ! No Change in your salary !")
        else :
            self.comp = self.comp*.9
            return (f"Sorry, 10% will be deducted from your compensation !, and final compensation is {round(self.comp,2)}")
        
        

In [37]:
obj=VmwFutureWork()          

New Object Created: <__main__.VmwFutureWork object at 0x7fd419def9b0>


In [38]:
obj.work_location(input("Enter your future work Location - City \n"),float(input("Enter your current compensation in LPA\n")))



Enter your future work Location - City 
Patiala
Enter your current compensation in LPA
10.9


'Sorry, 10% will be deducted from your compensation !, and final compensation is 9.81'

In [40]:
obj.loc

'Patiala'

### Example 1.2 (Where you can access variables of a class or class function through its object)

In [58]:
class VmwFutureWork2():
    def __init__(self):
        print(f"New Object Created: {self}")
        self.cities = ['Delhi','Mumbai','Bangalore','Hyderabad','others'] 
        self.__my_private_variable = "My Private Variable" 
        ## __ make a variable or a function private which can not be accessed outside the class ##

     
    def work_location(self): 
        print(self.__my_private_variable)
        loc = input(f"Enter your future work City from the following options: \n {self.cities}\n")
        comp = float(input("Enter your current component in LPA:\n"))
        if loc =='others':
            comp = round(comp*.9,3)
            return (f"Sorry, 10% will be deducted from your compensation !, and final compensation is {comp}")
        else :
            return("Hurray ! No Change in your salary !")            

In [59]:
my_obj = VmwFutureWork2()

New Object Created: <__main__.VmwFutureWork2 object at 0x7fd41a1779e8>


In [60]:
my_obj.work_location()

My Private Variable
Enter your future work City from the following options: 
 ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'others']
Delhi
Enter your current component in LPA:
10.9


'Hurray ! No Change in your salary !'

### Example 2

In [862]:
class NaturalNumberOperation :
    def __init__(self):
        pass;
    
    def num_init(self):
        self.mynum = int(input("Enter the number to calculate sum of square about that"))
        
    
    def sum_natural(self):
        return reduce(lambda x,y : x + y , [i**2 for i in range(1, self.mynum+1)] )

In [863]:
a = NaturalNumberOperation()

In [864]:
a.num_init()

Enter the number to calculate sum of square about that4


In [865]:
a.sum_natural()

30

# Inheritance 

### Basic Inheritance Example

In [19]:
class FatherClass:
    def __init__(self,name):
        self.name = name
     
    def print_name(self):
        self.i = 12
        print(f"I am {self.name}")
        
class SonClass(FatherClass):
    def print_i(self):
        print (father.i)
    

In [20]:
father=FatherClass("Father")
son=SonClass("Son")

In [21]:
father.print_name()

I am Father


In [22]:
son.print_name()

I am Son


In [23]:
son.print_i()

12


In [24]:
father.i

12

In [25]:
father.print_i()

AttributeError: 'FatherClass' object has no attribute 'print_i'

In [27]:
son.i

12

In [28]:
son.i = 14

In [29]:
father.i

12

In [30]:
father.i = 15

In [31]:
son.print_i()

15


In [32]:
son.i

14

In [33]:
father.i

15

In [40]:
class Animal:
    # properties
        def f(self):
            self.multicellular = True
        # Eukaryotic means Cells with Nucleus
            self.eukaryotic = True

In [41]:
class Cat(Animal):
    pass;

In [44]:
c = Cat()
a = Animal()

In [48]:
c.multicellular

AttributeError: 'Cat' object has no attribute 'multicellular'

In [46]:
a.f()

In [47]:
a.multicellular

True

In [49]:
c.a.multicellular

AttributeError: 'Cat' object has no attribute 'a'

In [50]:
c.multicellular = a.multicellular

In [51]:
c.multicellular

True

In [52]:
c.multicellular = False

In [53]:
a.multicellular

True

### Difference between type and isinstance()

In [ ]:
'''
isinstance()
 We see that isinstance returns True if we compare an object either with the class it belongs to 
 or with the superclass. 

type()
 Whereas the equality operator only returns True, if we compare an object with its own class.

'''

In [888]:
class A:
    pass
class B(A):
    pass
class C(B):
    pass   

In [890]:
a = A()
c = C() 

In [891]:
type(a)

__main__.A

In [892]:
type(c)

__main__.C

In [897]:
type(a) == type(c)

False

In [896]:
isinstance(c,A)

True

### Overriding

In [ ]:
## A method of a parent class gets overridden by simply defining a method with the same name in the child class.

## If a method is overridden in a class, the original method can still be accessed, 
## but we have to do it by calling the method directly with the class name


In [902]:
class FatherClass:
     
    def print_name(self):
        print("FatherClass")
        
class SonClass(FatherClass):
    def print_name(self):
        print("SonClass")
    

In [903]:
f = FatherClass()

In [904]:
f.print_name()

FatherClass


In [906]:
s = SonClass()

In [907]:
s.print_name()

SonClass


In [908]:
#### IMPORTANT

## Python has overwriting and not overloading

#### IMPORTANT

# Regular Experession



In [1]:
import re

In [ ]:
''''
RegEx Functions:-

1. findall - Returns a list containing all the matches (all the occurences)
2. search  - Returns a match object if there's a match in the string (returns only the first occurence)
3. split   - Returns a list based on the split criteria
4. sub     - Replaces one or many matches with a string 
5. match
6. escape
7. fullmatch
8. finditer
'''

### Split & findall Function

In [6]:
re_test = "This is a made up string to test regex"
re_test_messy = "This is     a     made   up  string  to test regex"
re_test_messy_more = "This-is-a made-***ip string to....test regex--"

In [4]:
re.split('\s',re_test)

['This', 'is', 'a', 'made', 'up', 'string', 'to', 'test', 'regex']

In [ ]:
## OR

In [17]:
re.findall('\S+',re_test)

['This', 'is', 'a', 'made', 'up', 'string', 'to', 'test', 'regex']

In [7]:
## looks for one or more spaces
re.split('\s+',re_test_messy)

['This', 'is', 'a', 'made', 'up', 'string', 'to', 'test', 'regex']

In [ ]:
## OR

In [12]:
re.findall('\S+',re_test_messy)

['This', 'is', 'a', 'made', 'up', 'string', 'to', 'test', 'regex']

In [13]:
## Looks for one or more non-word chars
re.split('\W+',re_test_messy_more)

['This', 'is', 'a', 'made', 'ip', 'string', 'to', 'test', 'regex', '']

In [ ]:
## OR

In [14]:
re.findall('\w+',re_test_messy_more)

['This', 'is', 'a', 'made', 'ip', 'string', 'to', 'test', 'regex']

### Replace a specific string using sub function

In [ ]:
#### Tasks :-
## 1. Replace PEP8 with PEP8 Python
## 2. Check for similar words and correct them to PEP8 Python, example PEP7 

In [20]:
pep8_test = 'I try to follow PEP8 guidelines'
pep7_test = 'I try to follow PEP7 guidelines'
peep8_test = 'I try to follow PEEP8 guidelines'

In [21]:
re.findall('[a-zA-Z0-9]+',pep8_test)

['I', 'try', 'to', 'follow', 'PEP8', 'guidelines']

In [23]:
print(re.findall('[A-Z]+[0-9]+',pep8_test))
print(re.findall('[A-Z]+[0-9]+',pep7_test))
print(re.findall('[A-Z]+[0-9]+',peep8_test))

['PEP8']
['PEP7']
['PEEP8']


In [24]:
re.sub('[A-Z]+[0-9]+','PEP8 Python',pep8_test)

'I try to follow PEP8 Python guidelines'

In [25]:
re.sub('[A-Z]+[0-9]+','PEP8 Python',pep7_test)

'I try to follow PEP8 Python guidelines'

In [26]:
re.sub('[A-Z]+[0-9]+','PEP8 Python',peep8_test)

'I try to follow PEP8 Python guidelines'

In [27]:
## For Lower Case too

pep7_test_lower = 'I try to follow pep8 guidelines'

In [30]:
re.sub('([A-Z]+|[a-z]+)[0-9]+','PEP8 Python',pep7_test_lower)

'I try to follow PEP8 Python guidelines'

# Detail of Package/library + Class & object + Function calling



In [ ]:
## For class & object + function calling check CPB Updated Automated ipynb



# Custom Loss Function in Keras and Light GBM


In [ ]:
## Check CPB Updated Automated ipynb for Light GBM

# Hyperopt Parameter Tuning 
### 1. Using Hyperopt

In [1]:
## Non-Standard Doc and Non-VCPP EULA notebooks

# ML Pipeline

In [ ]:
## Check BSC -Pipeline and Flask ipynb file in My Python Jupyter Notebook



# Model Deployment - Flask & Django

# pyspark

In [909]:
import pyspark

# Coding Practise

In [ ]:
## Return nth number of a fibonacci series ##
'''
The Fibonacci numbers are the numbers in the following integer sequence.
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ……..
0
0+1 = 1
1+0 = 1
1+1 = 2
2+1 = 3
3+2 = 5
5+3 = 8

In mathematical terms, the sequence Fn of Fibonacci numbers is defined by the recurrence relation 
'''

In [77]:
## Way 1 - Recrusion

def fib(n):
    if n == 1:
        return 0
    
    elif n == 2:
        return 1
    
    else: 
        return fib(n-1) + fib(n-2);

In [80]:
def main():
    print(fib(int(input("Enter the number for fibonacci series"))));

In [82]:
if __name__ == '__main__':main()

Enter the number for fibonacci series6
5


In [609]:
## Way 2 - Loop + Print the entire series

mysum1 = 0
mysum2 = 1
my_input= int(input())
print(mysum1)
print(mysum2)
for i in range(my_input-2):
    mysum  = mysum1 + mysum2
    mysum1 = mysum2
    mysum2 = mysum
    print(mysum)    

10
0
1
1
2
3
5
8
13
21
34


### 2 Palindrome Check

In [ ]:
## Check if an input string is a palindrome or not

In [632]:
mypal = input()

Sahil


In [636]:
mypal[:-2]

'Sah'

In [639]:
mypal[::-1] ## Reversing a list

'lihaS'

In [640]:
if list(mypal) == list(mypal)[::-1]:
    print("Palindrome")
else :
    print("Not a Palindrome")

Not a Palindrome


### 3 Sum of squares of first n natural numbers

In [ ]:
## Given a positive integer N. The task is to find 1^2 + 2^2 + 3^2 + ….. + N^2.

In [667]:
mynum = int(input())

5


In [668]:
## Way 1 : using in-built sum function

sum( [i**2 for i in range(1, mynum+1)])

55

In [670]:
## Way 2 : using reduce from functools

reduce(lambda x,y : x + y , [i**2 for i in range(1, mynum+1)] )

55

### 4 Armstrong Number

In [672]:
## Given a number x, determine whether the given number is Armstrong number or not. A positive integer of n digits is called an Armstrong number of order n (order is number of digits) if.

## abcd... = pow(a,n) + pow(b,n) + pow(c,n) + pow(d,n) + .... 


In [688]:
myarm = input()

1634


In [689]:
list(myarm)

['1', '6', '3', '4']

In [690]:
sum([int(i)**int(len(myarm)) for i in list(myarm)])

1634

In [691]:
if sum([int(i)**int(len(myarm)) for i in list(myarm)]) == int(myarm):
    print("Number is Armstrong")
else : 
    print("Number is not Armstrong")

Number is Armstrong


### 5  Prime Numbers in an interval

In [ ]:
## Given two positive integer start and end. 
## The task is to write a Python program toprint all Prime numbers in an Interval.

In [716]:
num1 = int(input())
num2 = int(input())
if num2 <= num1 :
    raise Exception("Second number can only be greater than First number")
elif num1 <3:
    raise Exception("First number can not be lesser than 3")

3
12


In [742]:
## Way 1

cnt = 0
for i in list(np.arange(num1+1,num2)):
    for j in range(2,i):
        if i%j==0:
            cnt = cnt + 1
            break;
    if cnt == 0:
        print(i)
    cnt = 0    


5
7
11


In [744]:
## Way 2 :- Using else condition with for loop (without any if)

cnt = 0
for i in list(np.arange(num1+1,num2)):
    for j in range(2,i):
        if i%j==0:
            break;
    else:
        print(i)



5
7
11


### 5 Monotonic Array Check

In [ ]:
### An array is monotonic if it is either monotone increasing or monotone decreasing.

In [71]:
def mono(myinput):
    pos = 0
    neg = 0
    cnt = 0
    for i in range(0,len(myinput)-2):
        diff1 = int(myinput[i+1]) - int(myinput[i])
        diff2 = int(myinput[i+2]) - int(myinput[i+1])
        if diff1 <=0 and diff2 <=0 :
            neg += 1
        elif diff1 >= 0 and diff2 >=0:
            pos += 1
        else :
            cnt +=1
            break;
    return pos,neg,cnt   

In [72]:

def main ():
    pos,neg,cnt=0,0,0
    pos,neg,cnt = mono(input("Enter each number followed by space\n").strip(" ").split())
    if ((pos > 0 & neg > 0) | cnt > 0) :
        print("Non-Monolithic")
    else:
        print("Monolithic")

In [76]:
if __name__ == '__main__' : main()

Enter each number followed by space
12 13 14 14 15 16 16
Monolithic


### 6 Floating number computation

In [83]:
## Problem

a = .1 + .1 + .1 - .3
print(a)

5.551115123125783e-17


In [84]:
## Solution

from decimal import *

In [85]:
x = Decimal('.10')
y = Decimal('.30') 

In [87]:
a = x + x + x - y
print (a)

0.00


### 7 Immutability in python

In [94]:
a = int(1)

In [95]:
id(a)

4443989632

In [97]:
a = int(3)

In [98]:
id(a)

4443989696

In [ ]:
## This is how int is immutable in Python
## a now points to 3, but 1 is still in memory.

In [105]:
x = (1,2,3)

In [107]:
try:
    print(x)
except:
    print("Error");

(1, 2, 3)


### 8 Recursive function to calculate sum of n numbers

In [1]:
num = int(input("Enter the number"))

Enter the number4


In [3]:
def fun_sum(num):
    
    if num<=1:
        return num
    else:
        return num + fun_sum(num-1)
    

In [5]:
fun_sum(num)

10

### 9 Count the amount of ones in the binary representation of an integer. For example, since 12 is 1100 in binary, the return value should be 2.

In [7]:
binary = input("Enter the binary number: ")

Enter the binary number: 101010101110001


In [11]:
def bin_zero(binary):
    count = 0;
    for i in binary:
        if int(i)==0:
            count+=1;
        else:
            pass;
    return count    

In [12]:
print(f'Number of zeros in binary number - {binary} are : {bin_zero(binary)}')

Number of zeros in binary number - 101010101110001 are : 7


In [26]:
import pandas as pd
import numpy as np

### 10 Create a function that takes a list and finds the integer which appears an odd number of times.

In [56]:
my_list = [1,4,4,3,1,1,7,-8,0,4]

In [57]:
def fun_odd(my_list):
    mydf = pd.DataFrame(my_list,columns=['numbers'])
    count = pd.DataFrame(mydf['numbers'].value_counts())
    count['index']=count.index
    return count
    

In [58]:
x = fun_odd(my_list)

In [59]:
list(x[x.numbers%2!=0]['index'])

[4, 1, 7, 3, 0, -8]

In [61]:
isinstance(my_list,list)

True

In [62]:
type(my_list) == list

True

### 11 Fullname and Email
#### Link : https://edabit.com/challenge/gB7nt6WzZy8TymCah